CREATE DATABASE IF NOT EXISTS AURORA;
USE AURORA;


-- game_starts table, will we used as a primary table
CREATE TABLE IF NOT EXISTS game_stats(
    PLAYER_ID CHAR(10) PRIMARY KEY,
    PLAYER_NAME VARCHAR(30),
    LEVEL INT,
    SCORE INT DEFAULT 0,
    BADGES TEXT DEFAULT 'No badges earned yet!',
    PROGRESS VARCHAR(3) DEFAULT '0%'
                                       );

-- this table holds data for troops that player has unlocked
CREATE TABLE IF NOT EXISTS player_troops(
    PLAYER_ID CHAR(10) NOT NULL UNIQUE,
    DELTA INT DEFAULT 1,
    TARDIS INT DEFAULT 0,
    BENZAMITE INT DEFAULT 0,
    MANDALORE INT DEFAULT 0,
    NEMESIS INT DEFAULT 0,
    ARMADA INT DEFAULT 0,
    ELSYIUM  INT DEFAULT 0,
    DEMOGORGON INT DEFAULT 0,
    FOREIGN KEY (PLAYER_ID) REFERENCES GAME_STATS(PLAYER_ID)
                                         );

-- this table holds data for spells that player has unlocked
CREATE TABLE IF NOT EXISTS player_spells(
    PLAYER_ID CHAR(10) NOT NULL UNIQUE,
    RAY_OF_SICKNESS INT DEFAULT 1,
    INCINERATE INT DEFAULT 0,
    PLASMA_DISCHARGE  INT DEFAULT 0,
    GOD_OF_CHAOS INT DEFAULT 0,
    FOREIGN KEY (PLAYER_ID) REFERENCES GAME_STATS(PLAYER_ID)
                                         );

-- details of troops and spells attack defence and spells
CREATE TABLE IF NOT EXISTS STATS(
    NAME VARCHAR(20) UNIQUE,
    ATTACK INT,
    DEFENCE INT,
    HP INT
);

CREATE TABLE IF NOT EXISTS SPELLS(
    PLAYER VARCHAR(20) UNIQUE,
    RAY_OF_SICKNESS INT,
    INCINERATE INT,
    PLASMA_DISCHARGE INT,
    GOD_OF_CHAOS INT
);

CREATE TABLE IF NOT EXISTS DELTA(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 10,
    DEFENCE INT DEFAULT 1,
    HEALTH INT DEFAULT 100
);

CREATE TABLE IF NOT EXISTS TARDIS(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 20,
    DEFENCE INT DEFAULT 2,
    HEALTH INT DEFAULT 200
);

CREATE TABLE IF NOT EXISTS BENZAMITE(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT  DEFAULT 40,
    DEFENCE INT DEFAULT 4,
    HEALTH INT DEFAULT 400
);

CREATE TABLE IF NOT EXISTS MANDALORE(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 60,
    DEFENCE INT  DEFAULT 6,
    HEALTH INT DEFAULT 600
);

CREATE TABLE IF NOT EXISTS NEMESIS(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 80,
    DEFENCE INT  DEFAULT 8,
    HEALTH INT DEFAULT 800
);

CREATE TABLE IF NOT EXISTS ARMADA(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 100,
    DEFENCE INT DEFAULT 10,
    HEALTH INT DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS ELYSIUM(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 120,
    DEFENCE INT DEFAULT 12,
    HEALTH INT DEFAULT 1200
);

CREATE TABLE IF NOT EXISTS DEMOGORGON(
    PLAYER VARCHAR(20) UNIQUE,
    ATTACK INT DEFAULT 150,
    DEFENCE INT DEFAULT 15,
    HEALTH INT DEFAULT 1500
);
